- id: '1755668156778'
  alias: Driveway - Smooth Sunset Fade
  description: Gradually fade in driveway lights starting 15 minutes before sunset
  triggers:
  - trigger: sun
    event: sunset
    offset: -00:15:00
  actions:
  - service: light.turn_on
    target:
      entity_id: light.driveway
    data:
      brightness_pct: 50
      transition: 900
  mode: single
- id: '1755668333675'
  alias: Driveway - Smooth Sunrise Fade Out
  description: Gradually fade out driveway lights starting 15 minutes after sunrise
  triggers:
  - trigger: sun
    event: sunrise
    offset: 00:15:00
  actions:
  - service: light.turn_off
    target:
      entity_id: light.driveway
    data:
      transition: 900
  mode: single
- id: security_lights_activate
  alias: Security Lights - Person/Vehicle Detected
  description: Activate security lighting when person or vehicle detected during night
    hours
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.driveway_af_person_detected
    - binary_sensor.driveway_af_vehicle_detected
    - binary_sensor.driveway_cdv_person_detected
    - binary_sensor.driveway_cdv_vehicle_detected
    - binary_sensor.g4_pro_person_detected
    - binary_sensor.g4_pro_vehicle_detected
    - binary_sensor.g4_doorbell_person_detected
    - binary_sensor.g4_doorbell_vehicle_detected
    to: 'on'
  conditions:
  - condition: sun
    after: sunset
    before: sunrise
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: timer.security_lights_timer
        state: idle
      sequence:
      - service: scene.create
        data:
          scene_id: security_lights_restore
          snapshot_entities:
          - light.driveway
          - light.front_porch_1
          - light.front_porch_2
          - light.front_porch_3
          - light.back_door_lantern
      - service: light.turn_on
        target:
          entity_id: light.driveway
        data:
          brightness_pct: 80
          transition: 5
      - service: light.turn_on
        target:
          entity_id:
          - light.front_porch_1
          - light.front_porch_2
          - light.front_porch_3
          - light.back_door_lantern
        data:
          brightness_pct: 100
          transition: 5
  - service: timer.start
    target:
      entity_id: timer.security_lights_timer
  mode: restart
- id: security_lights_reset
  alias: Security Lights - Reset After Timer
  description: Restore lights to original state after 5 minutes of no activity
  triggers:
  - trigger: event
    event_type: timer.finished
    event_data:
      entity_id: timer.security_lights_timer
  actions:
  - service: scene.turn_on
    target:
      entity_id: scene.security_lights_restore
    data:
      transition: 5
  - service: scene.delete
    target:
      entity_id: scene.security_lights_restore
  mode: single
- id: '1756056166666'
  alias: Camera Vision
  description: ''
  use_blueprint:
    path: valentinfrlch/event_summary.yaml
    input:
      camera_entities:
      - camera.g4_pro_high_2
      - camera.g3_bullet_high
      - camera.g4_pro_high_3
      - camera.g4_pro_high
      provider: 01K3EH5S6PF16B7X3ZRWVMW0FJ
      notify_device:
      - 83960fe87fb8b1c1bb5ab0a4de1b8011
      preview_mode: Live Preview
      notification_time: ''
      model: gemini-2.5-flash
- id: github_main_branch_auto_deploy
  alias: GitHub - Auto Deploy Main Branch Changes
  description: Automatically pull and reload Home Assistant configuration when main branch is updated
  triggers:
  - trigger: event
    event_type: github_push
    event_data:
      ref: refs/heads/main
  conditions:
  - condition: template
    value_template: "{{ trigger.event.data.repository.name == 'homeassistant' }}"
  actions:
  - service: shell_command.git_pull
  - delay: "00:00:05"
  - choose:
    - conditions:
      - condition: template
        value_template: >
          {{ trigger.event.data.commits | selectattr('modified') | 
             selectattr('modified', 'match', '.*automations\\.yaml$') | list | length > 0 }}
      sequence:
      - service: automation.reload
    - conditions:
      - condition: template
        value_template: >
          {{ trigger.event.data.commits | selectattr('modified') | 
             selectattr('modified', 'match', '.*scripts\\.yaml$') | list | length > 0 }}
      sequence:
      - service: script.reload
    - conditions:
      - condition: template
        value_template: >
          {{ trigger.event.data.commits | selectattr('modified') | 
             selectattr('modified', 'match', '.*scenes\\.yaml$') | list | length > 0 }}
      sequence:
      - service: scene.reload
    - conditions:
      - condition: template
        value_template: >
          {{ trigger.event.data.commits | selectattr('modified') | 
             selectattr('modified', 'match', '.*configuration\\.yaml$') | list | length > 0 }}
      sequence:
      - service: homeassistant.check_config
      - delay: "00:00:03"
      - service: homeassistant.reload_core_config
    - conditions:
      - condition: template
        value_template: >
          {{ trigger.event.data.commits | selectattr('modified') | 
             selectattr('modified', 'match', '.*/themes/.*\\.yaml$') | list | length > 0 }}
      sequence:
      - service: frontend.reload_themes
  - service: persistent_notification.create
    data:
      title: "🚀 Configuration Deployed"
      message: >
        Successfully deployed latest configuration from GitHub.
        Commit: {{ trigger.event.data.head_commit.message }}
        Author: {{ trigger.event.data.head_commit.author.name }}
      notification_id: github_deployment
  mode: single
